#!/usr/bin/env python3
"""
Nini Corporation — static site generator.

Emits plain HTML files with no runtime dependency. Deployment is still just
"upload the folder"; this script exists only so the header, footer and nav
stay identical across every page instead of being hand-edited 14 times.

    python build.py

Edit the CONTENT blocks below, re-run, and every page is rebuilt.
"""

import os, re

OUT = os.path.dirname(os.path.abspath(__file__))

SITE = {
    "name": "Nini Corporation",
    "tagline": "Complete Textiles Sourcing Solutions",
    "phone1": "+92-21-32411782",
    "phone2": "+92-21-32416077",
    "fax": "+92-21-32410286",
    "email": "sourcing@ninicorporation.com",
    "addr1": "M.R. 7/55, Adamjee Dawood Road",
    "addr2": "Karachi-74000, Pakistan",
    "founded": "1999",
}

# ── App integration ─────────────────────────────────────────────────────────
# Everything the site needs to hand off to the inspection app / client portal
# lives here. Leave a value blank and the site uses its own local behaviour;
# fill it in and re-run `python build.py` to point that piece at the app.
#
#   capability_pdf  URL the "Capability Statement (PDF)" button downloads from.
#                   Blank -> the local file generated by build_capability().
#   enquiry_url     Page the enquiry / sample buttons send people to.
#                   Blank -> the site's own contact.html#quote.
#   enquiry_api     Endpoint the contact form POSTs to (Formspree, or the app's
#                   own API). Blank -> the form validates but sends nothing.
#   portal_login    "Client Login" link in the header. Blank -> hidden.
APP = {
    "capability_pdf": "",
    "enquiry_url":    "",
    "enquiry_api":    "",
    "portal_login":   "",
}

PDF_HREF     = APP["capability_pdf"] or "nini-corporation-capability-statement.pdf"
PDF_DOWNLOAD = "" if APP["capability_pdf"] else " download"
ENQUIRY_HREF = APP["enquiry_url"] or "contact.html#quote"

NAV = [
    ("Home", "index.html", None),
    ("Company", None, [
        ("01", "About Us", "about.html"),
        ("02", "Why Choose Us", "why-choose-us.html"),
        ("03", "Our Process", "process.html"),
        ("04", "Industries We Serve", "industries.html"),
    ]),
    ("Services", None, [
        ("01", "Sourcing &amp; Inspection", "sourcing-inspection.html"),
        ("02", "Compliances", "compliances.html"),
        ("03", "Certifications", "certifications.html"),
        ("04", "Quality Assurance", "quality-assurance.html"),
        ("05", "Client Portal &amp; Reporting", "portal.html"),
    ]),
    ("Products", "products.html", None),
    ("Gallery", "gallery.html", None),
    ("Feedback", "feedback.html", None),
    ("Contact Us", "contact.html", None),
]

ARROW = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>'
TICK  = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><path d="m5 13 4 4L19 7"/></svg>'
CHEV  = '<svg class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>'

PROMO = {
    "Company":  ("assets/img/process-production.jpg", "Sourcing since 1999"),
    "Services": ("assets/img/process-inspection.jpg", "Four-point inspection"),
}


def nav_html(current):
    out = ['<nav class="nav" id="nav" aria-label="Primary">']
    for i, (label, href, subs) in enumerate(NAV):
        if subs:
            ddid = "dd-" + label.lower()
            active = " is-active" if any(current == s[2] for s in subs) else ""
            out.append('<div class="nav__item" data-dropdown>')
            out.append(f'<button class="nav__link{active}" type="button" aria-expanded="false" aria-controls="{ddid}">{label}{CHEV}</button>')
            out.append(f'<div class="dropdown" id="{ddid}"><ul class="dropdown__links">')
            for num, text, url in subs:
                out.append(f'<li><a href="{url}"><span class="num">{num}</span> {text}</a></li>')
            img, cap = PROMO[label]
            out.append('</ul>')
            out.append(f'<span class="dropdown__promo"><img src="{img}" alt="" width="1920" height="1072" loading="lazy"><span>{cap}</span></span>')
            out.append('</div></div>')
        else:
            active = " is-active" if current == href else ""
            out.append(f'<div class="nav__item"><a class="nav__link{active}" href="{href}">{label}</a></div>')
    out.append('<a class="pill nav__cta" href="contact.html#quote" style="display:none">Get a Quote</a>')
    out.append('</nav>')
    return "\n".join(out)


LOGIN_LINK = (f'<a class="util-link" href="{APP["portal_login"]}" rel="noopener">Client Login</a>'
              if APP["portal_login"] else '')


def header_html(current):
    return f'''<header class="header" id="header">
  <div class="container">
    <div class="header__top">
      <a class="brand" href="index.html" aria-label="{SITE['name']} — home">
        <img src="assets/img/mark-light.png" alt="" width="240" height="163" aria-hidden="true">
        <span>
          <span class="brand__name">{SITE['name']}</span>
          <span class="brand__tag">{SITE['tagline']}</span>
        </span>
      </a>
      <div class="header__utils">
        {LOGIN_LINK}<a class="util-link" href="contact.html">Contact</a>
        <a class="circle" href="contact.html#quote" aria-label="Request a quote">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M7 17 17 7M9 7h8v8"/></svg>
        </a>
        <a class="circle" href="products.html" aria-label="Browse products">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>
        </a>
        <button class="burger" type="button" aria-expanded="false" aria-controls="nav" aria-label="Open menu"><span></span></button>
      </div>
    </div>
{nav_html(current)}
  </div>
</header>'''


CTA_BAND = f'''<section class="section">
  <div class="container">
    <div class="split split--text-first">
      <div class="reveal">
        <p class="eyebrow">Get in touch</p>
        <h2 class="h2 statement">Ready for a Sourcing Partner That Checks Every Detail?</h2>
        <p class="lead" style="margin-top:1.2rem">Tell us what you need sourced, inspected or audited — we respond with next steps within one business day.</p>
        <div style="margin-top:2rem;display:flex;gap:.9rem;flex-wrap:wrap">
          <a class="pill" href="{ENQUIRY_HREF}">Request a Consultation {ARROW}</a>
          <a class="pill pill--ghost" href="{PDF_HREF}"{PDF_DOWNLOAD} type="application/pdf">
            <svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2.2" aria-hidden="true"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>
            Capability Statement (PDF)
          </a>
        </div>
      </div>
      <div class="feature__media reveal reveal--depth reveal-d1 clipreveal">
        <img src="assets/img/process-shipping.jpg" alt="Export cartons prepared for container loading" width="1920" height="1072" loading="lazy">
      </div>
    </div>
  </div>
</section>'''


def footer_html():
    cols = [
        ("Company",  [(t, u) for _, t, u in NAV[1][2]]),
        ("Services", [(t, u) for _, t, u in NAV[2][2]]),
        ("Explore",  [("Products", "products.html"), ("Gallery", "gallery.html"),
                      ("Feedback", "feedback.html"), ("Get a Quote", "contact.html#quote")]),
    ]
    colhtml = ""
    for title, links in cols:
        items = "".join(f'<li><a href="{u}">{t}</a></li>' for t, u in links)
        colhtml += f'<div><h4>{title}</h4><ul>{items}</ul></div>'

    return f'''<footer class="footer">
  <div class="container">
    <div class="footer__top">
      <div>
        <div class="footer__brand">
          <img src="assets/img/mark-light.png" alt="" width="240" height="163" aria-hidden="true">
          <span><strong>{SITE['name']}</strong><em>{SITE['tagline']}</em></span>
        </div>
        <p style="max-width:36ch">Sourcing and inspection services since {SITE['founded']} for companies across Europe, the United Kingdom and North America.</p>
        <p style="margin-top:1.2rem;font-size:.9rem">{SITE['addr1']}<br>{SITE['addr2']}</p>
      </div>
      {colhtml}
    </div>
    <div class="footer__wordmark">
      <p>Complete Peace of Mind, <em>Factory Floor to Your Door</em></p>
    </div>
    <div class="footer__bottom">
      <span>© {SITE['founded']}–<span id="year">2026</span> {SITE['name']}. All rights reserved.</span>
      <span class="footer__legal">
        <a href="faqs.html">FAQs</a>
        <a href="privacy-policy.html">Privacy</a>
        <a href="terms.html">Terms</a>
        <a href="mailto:{SITE['email']}">{SITE['email']}</a>
        <a href="tel:+922132411782">{SITE['phone1']}</a>
      </span>
    </div>
  </div>
</footer>'''


LIGHTBOX = '''<div class="lightbox" id="lightbox" role="dialog" aria-modal="true" aria-label="Media viewer">
  <button class="lightbox__close" id="lbClose" type="button" aria-label="Close viewer">
    <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M18 6 6 18M6 6l12 12"/></svg>
  </button>
  <div>
    <img id="lbImg" src="" alt="">
    <p class="lightbox__cap" id="lbCap"></p>
  </div>
</div>'''


TRAY = f'''<div class="tray" id="sampleTray">
  <div class="tray__panel" id="trayPanel">
    <h3>Sample Request</h3>
    <p class="tray__hint">Categories you have selected. They travel with you to the enquiry form.</p>
    <div class="tray__list" id="trayList"></div>
    <div class="tray__actions">
      <a class="pill" id="traySend" href="{ENQUIRY_HREF}">Request These Samples {ARROW}</a>
      <button class="tray__clear" type="button" id="trayClear">Clear list</button>
    </div>
  </div>
  <button class="tray__toggle" type="button" id="trayToggle" aria-expanded="false" aria-controls="trayPanel">
    <svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="2.2" aria-hidden="true"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4zM3 6h18M16 10a4 4 0 0 1-8 0"/></svg>
    Sample Request <span class="tray__count" id="trayCount">0</span>
  </button>
</div>'''


def page_hero(title, lead, img, crumb):
    return f'''<section class="pagehero">
  <div class="pagehero__media"><img src="{img}" alt="" width="1920" height="1072" fetchpriority="high"></div>
  <div class="container">
    <p class="crumbs"><a href="index.html">Home</a> <span>/</span> {crumb}</p>
    <h1 class="h1">{title}</h1>
    <p class="lead">{lead}</p>
  </div>
</section>'''


def render(filename, title, description, body, current=None):
    current = current or filename
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="theme-color" content="#000000">

<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:image" content="assets/img/og-image.jpg">
<meta name="twitter:card" content="summary_large_image">

<!-- Marks the document as script-enabled before first paint, so scroll-reveal
     styles never leave content stuck at opacity:0 when JS is off. -->
<script>document.documentElement.classList.add('js');</script>

<link rel="icon" href="assets/img/mark-dark.png" type="image/png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="assets/css/styles.css">

<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "{SITE['name']}",
  "description": "Sourcing, inspection and compliance services for international buyers since {SITE['founded']}.",
  "foundingDate": "{SITE['founded']}",
  "email": "{SITE['email']}",
  "telephone": "{SITE['phone1']}",
  "address": {{
    "@type": "PostalAddress",
    "streetAddress": "{SITE['addr1']}",
    "addressLocality": "Karachi",
    "postalCode": "74000",
    "addressRegion": "Sindh",
    "addressCountry": "PK"
  }},
  "areaServed": ["Europe", "United Kingdom", "North America"]
}}
</script>
</head>
<body>

<a class="skip-link" href="#main">Skip to main content</a>

<div class="stitch" aria-hidden="true">
  <div class="stitch__track"></div>
  <div class="stitch__thread" id="stitchThread"></div>
  <div class="stitch__needle" id="stitchNeedle"></div>
</div>
<div class="cursor-ring" id="cursorRing" aria-hidden="true"></div>
<div class="cursor-dot" id="cursorDot" aria-hidden="true"></div>

{header_html(current)}

<main id="main">
{body}
</main>

{footer_html()}

{LIGHTBOX}

{TRAY}

<script src="assets/js/main.js" defer></script>
</body>
</html>
'''
    path = os.path.join(OUT, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return len(html)


# ── shared content fragments ────────────────────────────────────────────────

SERVICES = [
    ("01", "Price Negotiation", "Price negotiations with local factories to secure maximum benefit for our clients."),
    ("02", "Lead-Time Planning", "Lead-time planning with vendors to keep every order on a realistic, tracked schedule."),
    ("03", "Daily Quality Monitoring", "In-line inspections, shade approvals, and trims &amp; accessories approval, every day."),
    ("04", "Production Monitoring", "Daily production tracking to ensure on-time deliveries at every stage."),
    ("05", "Pre-Shipment Inspection", "Pre-shipment inspection and container sealing to prevent issues before they reach you."),
    ("06", "Status Reporting", "Weekly status reports by email plus live online updates with a unique login."),
    ("07", "Shipment &amp; Logistics", "Shipment and logistics planning coordinated around your delivery windows."),
    ("08", "Documentation Review", "Vendor shipment documents checked and approved before bank submission for timely dispatch."),
]

PROCESS = [
    ("01", "Vendor Sourcing", "We identify and vet factories from our established vendor panel against your product and volume needs."),
    ("02", "Price &amp; Lead-Time Negotiation", "Terms negotiated directly with the factory to secure the best value and a realistic delivery schedule."),
    ("03", "Production Monitoring", "Daily quality and production monitoring, including in-line inspection, shade and trims approval."),
    ("04", "Compliance &amp; Audit", "Factory, social, security, technical and environmental audits against local, international or C-TPAT requirements."),
    ("05", "Pre-Shipment Inspection", "Final inspection and container sealing before goods leave the factory."),
    ("06", "Reporting &amp; Dispatch", "Weekly status reports, document verification, and shipment &amp; logistics coordination through to dispatch."),
]

QA = [
    ("01", "Four-Point Inspection", "Our standard fabric inspection system, with custom SOPs available for a client's specific requirements."),
    ("02", "Lab-Verified Yarn Testing", "Moisture content, weight, thin/thick places, neps, strength and hairiness measured against buyer tolerances via reputable labs."),
    ("03", "Daily In-Line Inspection", "Shade approvals, trims &amp; accessories approval and production monitoring, tracked daily through the order cycle."),
    ("04", "Pre-Shipment Inspection", "Final inspection and container sealing before goods leave the factory, avoiding problems before they reach you."),
]

INDUSTRIES = [
    ("01 — Capability", "Home Textiles", "Bath, bed and home textile sourcing across our full vendor panel — institutional and retail, regardless of order size."),
    ("02 — Capability", "Yarn &amp; Greige Fabric", "High-volume weaving units with in-house sizing, air jet and sulzer projectile looms, monitored daily through production."),
    ("03 — Capability", "Ready-to-Cut Woven", "Dyed, printed and yarn-dyed fabrics including denim, shirting and sheeting, in narrow and wider widths."),
    ("04 — Capability", "Ready-to-Cut Knit", "Tubular and open-width knits, tracked from yarn stage through to final packaging and testing."),
]

PRODUCTS = [
    ("product-bath-towels.jpg", "Home Textiles", "Bath Towels"),
    ("product-bathrobes.jpg", "Home Textiles", "Bathrobes"),
    ("product-kitchen-textiles.jpg", "Home Textiles", "Kitchen &amp; Tea Towels"),
    ("product-infant-textiles.jpg", "Home Textiles", "Terry Bibs &amp; Infant Shirts"),
    ("product-patient-gowns.jpg", "Institutional", "Patient Gowns"),
    ("product-thermal-blankets.jpg", "Institutional", "Thermal Blankets"),
    ("product-thermal-blankets-2.jpg", "Home Textiles", "Bath &amp; Body Blankets"),
]

TESTIMONIALS = [
    ("IM", "Import Manager", "European Home Textiles Buyer",
     "Nini Corporation's daily production monitoring meant we always knew exactly where our order stood — no surprises at shipment."),
    ("CD", "Compliance Director", "UK Retail Group",
     "Their factory audit checklist caught safety issues we would never have seen from overseas. That's the value of a team on the ground."),
    ("SL", "Sourcing Lead", "North American Distributor",
     "Weekly status reports and a live online login kept our whole team aligned across three time zones."),
]


def approach_grid(items, extra=""):
    cells = "".join(
        f'<article class="approach__item"><p class="approach__num">{n}</p>'
        f'<h3 class="h4">{t}</h3><p>{d}</p></article>'
        for n, t, d in items)
    return f'<div class="approach {extra} stagger">{cells}</div>'


def process_grid(items):
    cells = "".join(
        f'<div class="process__step"><p class="process__num">STEP {n}</p>'
        f'<h3>{t}</h3><p>{d}</p></div>'
        for n, t, d in items)
    return f'<div class="process process--6 stagger">{cells}</div>'


def products_grid():
    out = []
    for i, (img, cat, name) in enumerate(PRODUCTS):
        wide = " product--wide" if i == len(PRODUCTS) - 1 else ""
        plain = re.sub("&amp;", "and", name)
        # an <article> wrapper: a <button> nested inside an <a> is invalid HTML,
        # so the link becomes a positioned overlay instead
        out.append(
            f'<article class="product{wide} tilt3d">'
            f'<img class="tilt3d__inner" src="assets/img/{img}" alt="{plain}" width="1200" height="1200" loading="lazy">'
            f'<a class="product__link" href="{ENQUIRY_HREF}" aria-label="Enquire about {plain}"></a>'
            f'<button class="product__add" type="button" data-sample="{plain}" aria-pressed="false" '
            f'aria-label="Add {plain} to sample request">'
            f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">'
            f'<path d="M12 5v14M5 12h14"/></svg></button>'
            f'<span class="product__cap"><span>{cat}</span><h3>{name}</h3></span></article>')
    return '<div class="products stagger stagger--tilt">' + "".join(out) + '</div>'


GALLERY_ITEMS = [
    ("process-production.jpg", "Production floor", "gallery__item--lg", "Production floor with industrial sewing machines"),
    ("process-inspection.jpg", "Quality inspection", "gallery__item--wide", "Quality inspection bench"),
    ("product-bath-towels.jpg", "Bath towels", "", "Bath towels"),
    ("product-bathrobes.jpg", "Bathrobes", "", "Bathrobes"),
    ("process-shipping.jpg", "Export and shipping", "gallery__item--wide", "Export cartons ready for shipping"),
    ("product-kitchen-textiles.jpg", "Kitchen textiles", "", "Kitchen textiles"),
    ("product-infant-textiles.jpg", "Infant textiles", "", "Infant textiles"),
]


def gallery_grid():
    out = []
    for img, cap, mod, alt in GALLERY_ITEMS:
        out.append(
            f'<button class="gallery__item {mod}" data-lightbox="assets/img/{img}" '
            f'data-caption="{cap}" aria-label="View larger image: {cap}">'
            f'<img src="assets/img/{img}" alt="{alt}" width="1600" height="1200" loading="lazy"></button>')
    return '<div class="gallery stagger">' + "".join(out) + '</div>'


def testimonials_block():
    slides = ""
    for i, (ini, name, role, quote) in enumerate(TESTIMONIALS):
        slides += (f'<div class="testi__slide" role="group" aria-roledescription="slide" aria-label="{i+1} of {len(TESTIMONIALS)}">'
                   f'<blockquote class="testi__quote">“{quote}”</blockquote>'
                   f'<div class="testi__by"><span class="testi__avatar" aria-hidden="true">{ini}</span>'
                   f'<span><span class="testi__name">{name}</span><br><span class="testi__role">{role}</span></span></div></div>')
    return f'''<div class="testi reveal reveal-d1">
  <div class="testi__viewport">
    <!-- TODO: these are UNATTRIBUTED (role + market only). Replace with real,
         named, permissioned quotes before publishing, or remove the section. -->
    <div class="testi__track" id="testiTrack">{slides}</div>
  </div>
  <div class="testi__arrows">
    <button class="circle circle--lg" type="button" id="testiPrev" aria-label="Previous testimonial">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
    </button>
    <button class="circle circle--lg" type="button" id="testiNext" aria-label="Next testimonial">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
    </button>
  </div>
  <p class="sr-only" role="status" aria-live="polite" id="testiStatus">Testimonial 1 of {len(TESTIMONIALS)}</p>
</div>'''


REPORT_CARD = '''<div class="reportcard">
  <div class="reportcard__head">
    <img src="assets/img/mark-light.png" alt="" aria-hidden="true">
    <span class="reportcard__tag">PDF Report</span>
  </div>
  <dl>
    <div class="reportcard__row"><dt>Order reference</dt><dd>—</dd></div>
    <div class="reportcard__row"><dt>Inspection stage</dt><dd>Pre-shipment</dd></div>
    <div class="reportcard__row"><dt>Standard</dt><dd>Four-point / AQL</dd></div>
    <div class="reportcard__row"><dt>Inspector</dt><dd>On site</dd></div>
  </dl>
  <div class="reportcard__bars" aria-hidden="true">
    <div class="reportcard__bar"><span style="width:82%"></span></div>
    <div class="reportcard__bar"><span style="width:64%"></span></div>
    <div class="reportcard__bar"><span style="width:93%"></span></div>
  </div>
  <p class="reportcard__foot">Photographic evidence attached</p>
</div>'''


FORM_ACTION = f' action="{APP["enquiry_api"]}" method="POST"' if APP["enquiry_api"] else ''

CONTACT_FORM = f'''<form class="form reveal reveal-d1" id="quoteForm" novalidate{FORM_ACTION}>
  <div class="form__grid">
    <div class="field"><label for="f-name">Full name <span class="req">*</span></label>
      <input id="f-name" name="name" type="text" autocomplete="name" required aria-describedby="e-name">
      <span class="field__err" id="e-name">Please enter your name.</span></div>
    <div class="field"><label for="f-company">Company name <span class="req">*</span></label>
      <input id="f-company" name="company" type="text" autocomplete="organization" required aria-describedby="e-company">
      <span class="field__err" id="e-company">Please enter your company.</span></div>
    <div class="field"><label for="f-email">Email address <span class="req">*</span></label>
      <input id="f-email" name="email" type="email" autocomplete="email" required aria-describedby="e-email">
      <span class="field__err" id="e-email">Please enter a valid email address.</span></div>
    <div class="field"><label for="f-phone">Phone number</label>
      <input id="f-phone" name="phone" type="tel" autocomplete="tel"></div>
    <div class="field"><label for="f-city">City</label>
      <input id="f-city" name="city" type="text" autocomplete="address-level2"></div>
    <div class="field"><label for="f-country">Country</label>
      <input id="f-country" name="country" type="text" autocomplete="country-name"></div>
    <div class="field field--full"><label for="f-service">What do you need?</label>
      <select id="f-service" name="service">
        <option value="">Select a service…</option>
        <option>Home textiles sourcing</option>
        <option>Yarn &amp; greige fabric</option>
        <option>Ready-to-cut woven fabric</option>
        <option>Ready-to-cut knit fabric</option>
        <option>Factory / social / security audit</option>
        <option>Pre-shipment inspection</option>
        <option>Certification consultation</option>
        <option>Other / multiple</option>
      </select></div>
    <div class="field field--full"><label for="f-msg">Comment <span class="req">*</span></label>
      <textarea id="f-msg" name="message" required aria-describedby="h-msg e-msg"></textarea>
      <span class="field__hint" id="h-msg">Include product, quantity, target price and required delivery date if known.</span>
      <span class="field__err" id="e-msg">Please tell us what you need.</span></div>
  </div>
  <div class="form__foot">
    <button class="pill" type="submit">Send Enquiry {ARROW}</button>
    <!-- TODO: connect to a mail handler — see README -->
    <p class="form__note">This form is not yet connected to a mail service — see the handover notes.</p>
    <p class="form__status" id="formStatus" role="status" aria-live="polite"></p>
  </div>
</form>'''


CONTACT_DETAILS = f'''<dl class="infolist">
  <div class="infolist__row">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0z"/><circle cx="12" cy="10" r="3"/></svg>
    <div><dt>Office</dt><dd>{SITE['addr1']}<br>{SITE['addr2']}</dd></div>
  </div>
  <div class="infolist__row">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.2a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2z"/></svg>
    <div><dt>Telephone</dt><dd><a href="tel:+922132411782">{SITE['phone1']}</a><br><a href="tel:+922132416077">{SITE['phone2']}</a></dd></div>
  </div>
  <div class="infolist__row">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 7 10 6 10-6"/></svg>
    <div><dt>Email</dt><dd><a href="mailto:{SITE['email']}">{SITE['email']}</a></dd></div>
  </div>
  <div class="infolist__row">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>
    <div><dt>Fax</dt><dd>{SITE['fax']}</dd></div>
  </div>
</dl>'''


# ── pages ───────────────────────────────────────────────────────────────────

def build_index():
    quick = ""
    for i, (img, label, url) in enumerate([
        ("product-bath-towels.jpg", "Products", "products.html"),
        ("product-patient-gowns.jpg", "Industries", "industries.html"),
        ("process-production.jpg", "Services", "sourcing-inspection.html"),
    ]):
        quick += (f'<a class="quicklink tilt3d" href="{url}">'
                  f'<img class="tilt3d__inner" src="assets/img/{img}" alt="" width="1200" height="1200" loading="lazy">'
                  f'<h3 class="h3">{label}</h3>'
                  f'<span class="explore">Explore <span class="circle" aria-hidden="true">{ARROW}</span></span></a>')

    slides = [
        ("hero-poster.jpg", True,  "Complete Peace of Mind", "Factory Floor to Your Door",
         f"Sourcing and inspection services since {SITE['founded']} for companies across Europe, the United Kingdom and North America — vendor negotiation, production monitoring, compliance auditing and pre-shipment inspection."),
        ("process-inspection.jpg", False, "Inspected On Site", "Reported the Same Day",
         "Our inspectors work from a dedicated quality inspection app on the factory floor. Every inspection becomes a documented PDF report in your portal — evidence, not reassurance."),
        ("process-shipping.jpg", False, "Sourced in Karachi", "Shipped Worldwide",
         "Container loading supervision, export documentation and logistics coordination through to your port of destination — with weekly status reporting throughout."),
    ]

    # Arrows removed at the client's request, so extra slides would be
    # unreachable — the hero is the video slide alone. Raise this to 3 (and
    # restore the arrow block below) to bring the carousel back.
    HERO_SLIDE_COUNT = 1
    slides = slides[:HERO_SLIDE_COUNT]

    slide_html = ""
    copy_html = ""
    for i, (img, has_video, l1, l2, sub) in enumerate(slides):
        # `autoplay` must be a real attribute, not just a JS .play() call:
        # iOS Safari only grants gesture-free playback to a muted + playsinline
        # element that declares it, and preload="none" gave it nothing to start
        # from. H.264 is listed first because Safari's WebM support is patchy.
        vid = (f'''<video id="heroVideo" autoplay muted loop playsinline
               preload="auto" poster="assets/img/{img}" aria-hidden="true"
               disablepictureinpicture disableremoteplayback>
          <source src="assets/video/backdrop.mp4" type="video/mp4">
          <source src="assets/video/backdrop.webm" type="video/webm">
        </video>''' if has_video else "")
        loadattr = ' fetchpriority="high"' if i == 0 else ' loading="lazy"'
        # First slide is marked active in the markup so the hero paints
        # correctly before JS runs — and still paints if JS never runs.
        act = " is-active" if i == 0 else ""
        hid = "false" if i == 0 else "true"
        slide_html += (f'<div class="heroslide{act}" aria-hidden="{hid}">'
                       f'<img src="assets/img/{img}" alt="" width="1920" height="1072"'
                       f'{loadattr}>{vid}</div>')
        copy_html += f'''<div class="hero__copyset{act}" aria-hidden="{hid}">
          <h1 class="h1 hero__title is-in">
            <span class="line-mask"><span>{l1}</span></span>
            <em class="line-mask"><span>{l2}</span></em>
          </h1>
          <p class="hero__sub">{sub}</p>
          <div class="hero__actions">
            <a class="pill" href="{ENQUIRY_HREF}">Request a Consultation {ARROW}</a>
            <a class="hero__scrollcue" href="#intro" aria-label="Scroll to content">
              <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 5v14M5 12l7 7 7-7"/></svg>
            </a>
          </div>
        </div>'''

    body = f'''<section class="hero" id="home">
  <div class="hero__media">{slide_html}</div>
  <div class="hero__scrim"></div>

  <div class="container hero__inner">
    <div class="hero__row">
      <div class="hero__left">
        <div class="roundel float" aria-hidden="true">
          <svg class="roundel__spin" viewBox="0 0 100 100">
            <defs><path id="roundelPath" d="M 50,50 m -39,0 a 39,39 0 1,1 78,0 a 39,39 0 1,1 -78,0"></path></defs>
            <text><textPath href="#roundelPath">SOURCING · INSPECTION · COMPLIANCE · SINCE 1999 · </textPath></text>
          </svg>
          <img src="assets/img/mark-dark.png" alt="" width="240" height="163">
        </div>
        <p class="eyebrow">Sourcing · Inspection · Compliance since {SITE['founded']}</p>
        <div class="hero__copy">{copy_html}</div>
      </div>
    </div>
  </div>
</section>

<section class="section expertise" id="intro">
  <div class="container">
    <p class="eyebrow reveal">Introduction</p>
    <h2 class="h2 reveal reveal-d1">{SITE['founded']} to Today — A Partner Built on Trust</h2>
    <p class="lead reveal reveal-d2">We represent international buyers on the ground in Karachi. Not a trading intermediary, but your quality, compliance and delivery team sitting inside the supply chain.</p>
    <div class="expertise__actions reveal reveal-d3">
      <a class="pill" href="about.html">About Nini {ARROW}</a>
      <a class="pill pill--ghost" href="process.html">See Our Process</a>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="statrow stagger">
      <div class="statrow__item"><p class="statrow__val"><span class="statrow__num" data-count="25">0</span><span>+</span></p><p class="statrow__key">Years in business</p></div>
      <div class="statrow__item"><p class="statrow__val"><span class="statrow__num" data-count="1000">0</span><span>+</span></p><p class="statrow__key">Factory audits conducted</p></div>
      <div class="statrow__item"><p class="statrow__val"><span class="statrow__num" data-count="3">0</span></p><p class="statrow__key">Continents served</p></div>
      <div class="statrow__item"><p class="statrow__val"><span class="statrow__num" data-count="1999" data-count-plain data-count-from="1970">0</span></p><p class="statrow__key">Established</p></div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container"><div class="quicklinks stagger stagger--tilt">{quick}</div></div>
</section>

<section class="section">
  <div class="container">
    <div class="section--pad">
      <p class="eyebrow reveal">What We Do</p>
      <h2 class="h2 statement--wide reveal reveal-d1" style="margin-bottom:2.5rem">End-to-End Sourcing, Managed by Our Team on the Ground</h2>
    </div>
    {approach_grid(SERVICES[:4], "approach--8")}
    <div style="margin-top:2.2rem"><a class="pill pill--ghost" href="sourcing-inspection.html">All Eight Services {ARROW}</a></div>
  </div>
</section>

<div class="marquee" aria-hidden="true">
  <div class="marquee__track">
    <span>Sourcing</span><span>Inspection</span><span>Compliance</span><span>Quality Assurance</span><span>Since 1999</span>
    <span>Sourcing</span><span>Inspection</span><span>Compliance</span><span>Quality Assurance</span><span>Since 1999</span>
  </div>
</div>

<section class="weaveband">
  <canvas class="weaveband__canvas" id="weaveCanvas" aria-hidden="true"></canvas>
  <div class="weaveband__inner">
    <p class="eyebrow reveal">Warp &amp; Weft</p>
    <h2 class="h2 reveal reveal-d1">Every Thread Accounted For</h2>
    <p class="lead reveal reveal-d2">Cloth is only as good as the threads that cross in it. The same is true of a supply chain — which is why we check the yarn, the loom, the line and the container, not just the carton at the end.</p>
    <p class="weaveband__hint reveal reveal-d3" aria-hidden="true">Move your cursor across the weave</p>
  </div>
</section>

<section class="section portal">
  <div class="container">
    <div class="portal__grid">
      <div class="reveal">
        <p class="eyebrow">What Sets Us Apart</p>
        <h2 class="h2 statement">Our Inspection App and Client Portal</h2>
        <p class="lead" style="margin-top:1.3rem">This is the difference between us and every other buying house you could appoint. Not a promise that quality is being watched — a system that proves it, inspection by inspection.</p>
        <ul class="feature__list" style="margin-top:1.6rem">
          <li>{TICK}<span><strong>A mobile app our auditors work from</strong> — AQL sample sizes and accept/reject limits calculated, pass or fail decided against the standard, every defect photographed and tagged.</span></li>
          <li>{TICK}<span><strong>A web portal for you</strong> — every report searchable by PO, item, vendor or date, with vendor pass rates and defect trends built from your own order history.</span></li>
          <li>{TICK}<span><strong>The report before the auditor leaves the factory</strong> — signed on site by inspector and factory representative, issued as PDF, in your portal the same day.</span></li>
        </ul>
        <div style="margin-top:2rem"><a class="pill" href="portal.html">See How It Works {ARROW}</a></div>
      </div>
      <div class="reveal reveal--depth reveal-d1">{REPORT_CARD}</div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="split split--text-first feature">
      <div class="reveal">
        <p class="eyebrow">Why Choose Nini</p>
        <h2 class="h2 statement">A Partner That Holds the Line on Quality</h2>
        <ul class="feature__list">
          <li>{TICK}<span><strong>Rigorous compliance.</strong> Factory, social, security, technical and environmental audits to C-TPAT and international standards.</span></li>
          <li>{TICK}<span><strong>Daily quality control.</strong> In-line inspection, shade approvals and production monitoring, every day of the order cycle.</span></li>
          <li>{TICK}<span><strong>International reach.</strong> Trusted across Europe, the UK and North America for over two decades.</span></li>
          <li>{TICK}<span><strong>On time, every time.</strong> Lead-time planning and weekly status reporting keep every shipment on schedule.</span></li>
          <li>{TICK}<span><strong>Our own quality management system.</strong> A mobile inspection app and client portal that no comparable buying house in the region offers.</span></li>
        </ul>
        <div style="margin-top:2rem"><a class="pill pill--ghost" href="why-choose-us.html">More Reasons {ARROW}</a></div>
      </div>
      <div class="feature__media reveal reveal--depth reveal-d1 clipreveal">
        <img src="assets/img/process-inspection.jpg" alt="Quality inspection of finished goods before shipment" width="1920" height="1072" loading="lazy">
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section--pad">
      <p class="eyebrow reveal">Our Vendor Panel</p>
      <h2 class="h2 statement reveal reveal-d1">The Network Behind Every Order</h2>
      <p class="lead reveal reveal-d2" style="margin-top:1.3rem;max-width:58ch;margin-bottom:2.5rem">
        We do not place orders with whoever is cheapest this month. Our panel is built from
        reputable vendors we have qualified, audited and worked with — and it is the reason we
        can take an order without gambling on the outcome.
      </p>
    </div>
    {approach_grid([
      ("01","Qualified, Not Just Listed","Every mill on the panel has been visited, audited and assessed against social, security and technical requirements before it sees a purchase order."),
      ("02","High-Volume Weaving","Greige vendors are high-volume units with in-house sizing and weaving — air jet and sulzer projectile — so capacity is real, not brokered."),
      ("03","Institutional and Retail","Most of our panel produces institutional and retail lines, which means we can place your programme regardless of order size."),
      ("04","Continuously Re-Audited","A vendor does not pass once and stay approved. Compliance is re-checked as programmes run, with corrective action planning when it slips."),
    ], "approach--8")}
    <div style="margin-top:2.2rem;display:flex;gap:.9rem;flex-wrap:wrap">
      <a class="pill pill--ghost" href="compliances.html">How We Audit {ARROW}</a>
      <a class="pill pill--ghost" href="industries.html">What They Make</a>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <p class="eyebrow reveal">Client Feedback</p>
    {testimonials_block()}
  </div>
</section>

{CTA_BAND}'''
    return render("index.html", f"{SITE['name']} | Sourcing, Inspection &amp; Compliance Since {SITE['founded']}",
                  f"Sourcing and inspection services since {SITE['founded']} for companies across Europe, the United Kingdom and North America.",
                  body)


def build_subpages():
    sizes = {}

    # About
    body = page_hero("A Partner Built on Trust",
                     f"Founded in {SITE['founded']}, Nini Corporation has provided sourcing and inspection services to companies across Europe, the United Kingdom and North America for over two decades.",
                     "assets/img/process-production.jpg", "About Us") + f'''
<section class="section">
  <div class="container">
    <div class="split split--text-first">
      <div class="reveal">
        <p class="eyebrow">Who We Are</p>
        <h2 class="h2 statement">The Bridge Between Buyers and Manufacturers</h2>
        <p class="body" style="margin-top:1.2rem">We represent international buyers on the ground in Karachi — Pakistan's textile and port capital. We are not a trading intermediary. We are your quality, compliance and delivery team, sitting between your purchase order and the factory floor.</p>
        <div class="mv">
          <div class="mv__item"><h3 class="h4">Our Mission</h3><p>To provide complete peace of mind to our foreign clients through disciplined sourcing, rigorous quality control and transparent reporting.</p></div>
          <div class="mv__item"><h3 class="h4">Our Vision</h3><p>To be the trusted bridge between international buyers and manufacturing partners — reliable, compliant, and built on decades of relationships.</p></div>
        </div>
      </div>
      <div class="feature__media reveal reveal--depth reveal-d1 clipreveal">
        <img src="assets/img/process-production.jpg" alt="Production floor at a partner manufacturing unit" width="1920" height="1072" loading="lazy">
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section--pad">
      <p class="eyebrow reveal">Global Presence</p>
      <h2 class="h2 statement reveal reveal-d1" style="margin-bottom:2.5rem">Karachi-Based, Connected to Buyers on Three Continents</h2>
    </div>
    {approach_grid([("01","Europe","Home textile buyers across Western and Central Europe."),
                    ("02","United Kingdom","Retail and institutional textile programmes sourced and audited from Karachi."),
                    ("03","North America","Distributors and importers relying on our pre-shipment inspection network.")])}
  </div>
</section>
{CTA_BAND}'''
    sizes["about.html"] = render("about.html", f"About Us | {SITE['name']}",
        f"Founded in {SITE['founded']}, Nini Corporation provides sourcing and inspection services to buyers in Europe, the UK and North America.", body)

    # Why choose us
    body = page_hero("Why Buyers Choose Nini",
                     "A vendor management partner that holds the line on quality — and carries the risk your merchandising team should not have to.",
                     "assets/img/process-inspection.jpg", "Why Choose Us") + f'''
<section class="section">
  <div class="container">
    {approach_grid([
      ("01","Rigorous Compliance","Factory, social, security, technical and environmental audits to C-TPAT and international standards — verified before your first order, not after a failed audit."),
      ("02","Daily Quality Control","In-line inspection, shade approvals and production monitoring, every single day of the order cycle."),
      ("03","International Reach","Trusted by clients across Europe, the United Kingdom and North America for over two decades."),
      ("04","On Time, Every Time","Lead-time planning and weekly status reporting keep every shipment on schedule."),
      ("05","Single Accountability","One team owns sourcing, quality, compliance and shipment — no finger-pointing between agent, mill and forwarder."),
      ("06","Our Own Quality Management System","A mobile inspection app our auditors work from and a web portal you log into — automated AQL, photographic evidence, instant PDF reports and searchable quality history. Our single biggest point of difference."),
    ], "approach--8")}
  </div>
</section>
{CTA_BAND}'''
    sizes["why-choose-us.html"] = render("why-choose-us.html", f"Why Choose Us | {SITE['name']}",
        "Rigorous compliance, daily quality control and two decades of international reach.", body)

    # Process
    # scroll-pinned: the frame stays put while the six steps scroll past it
    pin_shots = ["process-production.jpg", "process-inspection.jpg", "process-production.jpg",
                 "process-inspection.jpg", "product-bath-towels.jpg", "process-shipping.jpg"]
    shots_html = ""
    for k, im in enumerate(pin_shots):
        cur = "is-current" if k == 0 else ""
        la = ' fetchpriority="high"' if k == 0 else ' loading="lazy"'
        shots_html += (f'<img class="{cur}" src="assets/img/{im}" alt="" '
                       f'width="1600" height="1200"{la}>')
    steps_html = "".join(
        f'<div class="pinned__step{" is-current" if k == 0 else ""}">'
        f'<p class="process__num">STEP {n}</p><h3>{t}</h3><p>{d}</p></div>'
        for k, (n, t, d) in enumerate(PROCESS))

    body = page_hero("Six Steps, One Accountable Team",
                     "The same disciplined process runs behind every order — negotiation, monitoring, auditing, inspection and reporting.",
                     "assets/img/process-production.jpg", "Our Process") + f'''
<section class="section">
  <div class="container">
    <div class="pinned">
      <div class="pinned__media">
        <div class="pinned__frame">
          {shots_html}
          <p class="pinned__counter" id="pinnedCounter">01<span>/06</span></p>
        </div>
      </div>
      <div class="pinned__steps">{steps_html}</div>
    </div>
  </div>
</section>
{CTA_BAND}'''
    sizes["process.html"] = render("process.html", f"Our Process | {SITE['name']}",
        "From vendor sourcing to dispatch — the six controlled stages behind every order.", body)

    # Industries
    cells = "".join(f'<div class="logogrid__cell"><span>{a}</span><strong>{b}</strong><p>{c}</p></div>' for a, b, c in INDUSTRIES)
    body = page_hero("Textiles, End to End",
                     "We are a textile specialist. Four connected capability areas, one vendor panel, and a team that understands every stage between the spinning frame and the sealed container.",
                     "assets/img/product-infant-textiles.jpg", "Industries We Serve") + f'''
<section class="section">
  <div class="container">
    <div class="logogrid stagger">{cells}</div>
    <p class="pullquote reveal">Serving retail, institutional and apparel buyers across Europe, the United Kingdom and North America — with pre-shipment inspection available to apparel clients on request.</p>
  </div>
</section>
{CTA_BAND}'''
    sizes["industries.html"] = render("industries.html", f"Industries We Serve | {SITE['name']}",
        "Home textiles, yarn and greige fabric, ready-to-cut woven and knit fabric.", body)

    # Services
    body = page_hero("End-to-End Sourcing Services",
                     "Eight services, managed by our team on the ground in Karachi — from the first price negotiation to the sealed container.",
                     "assets/img/process-production.jpg", "Sourcing &amp; Inspection") + f'''
<section class="section"><div class="container">{approach_grid(SERVICES, "approach--8")}</div></section>
{CTA_BAND}'''
    sizes["sourcing-inspection.html"] = render("sourcing-inspection.html", f"Sourcing &amp; Inspection | {SITE['name']}",
        "Price negotiation, lead-time planning, daily monitoring, pre-shipment inspection and more.", body)

    # Compliances
    risks = "".join(f'<li>{r}</li>' for r in [
        "Open lift gates", "Emergency exits &amp; staircases blocked", "Expired fire extinguishers",
        "Unhygienic drinking water", "Chemicals stored without safety"])
    tags = "".join(f'<li>{t}</li>' for t in [
        "Personnel security", "Security awareness training", "Risk assessment",
        "Conveyance security inspection", "Physical security", "Procedural security",
        "Information technology", "Business partners", "Physical access controls"])
    body = page_hero("Would You Like to Know Your Suppliers Actually Comply?",
                     "Our factory audit teams check social, security, technical and environmental compliance — so risks never reach your supply chain.",
                     "assets/img/process-shipping.jpg", "Compliances") + f'''
<section class="section">
  <div class="container">
    <ul class="riskrow stagger">{risks}</ul>
    <div class="split" style="margin-top:clamp(2.5rem,5vw,4rem)">
      <div class="reveal">
        <h3 class="h3" style="margin-bottom:1.2rem">Social Compliance Audit</h3>
        <p class="body">Based on local and international requirements — health &amp; safety, compensation, and the prohibition of child labour, harassment, abuse, forced labour and discrimination.</p>
        <ul class="feature__list" style="margin-top:1.4rem">
          <li>{TICK}<span>Supplier evaluation, subordinate supplier review and confirmation of your exact production location</span></li>
          <li>{TICK}<span>Factory tour covering health, safety and emergency evacuation adequacy</span></li>
          <li>{TICK}<span>Worker interviews and review of benefits and rights records against local and international law</span></li>
        </ul>
      </div>
      <div class="reveal reveal-d1">
        <h3 class="h3" style="margin-bottom:1.2rem">Security Compliance Audit</h3>
        <p class="body">Based on C-TPAT and global security requirements, covering the full scope of supply-chain security controls.</p>
        <ul class="tagrow" style="margin-top:1.4rem">{tags}</ul>
      </div>
    </div>
    <p class="pullquote reveal">“We conduct audits to the customer's own checklist. If you don't have one, we use ours — which comprehensively covers all audit requirements.”</p>
  </div>
</section>
{CTA_BAND}'''
    sizes["compliances.html"] = render("compliances.html", f"Compliances | {SITE['name']}",
        "Factory, social, security, technical and environmental audits to C-TPAT and international standards.", body)

    # Certifications
    body = page_hero("Getting Textile Suppliers Certified, Not Just Audited",
                     "Consultation on sustainable management, social and quality systems across the textile supply chain.",
                     "assets/img/process-shipping.jpg", "Certifications") + f'''
<section class="section">
  <div class="container">
    <div class="split split--text-first">
      <div class="reveal">
        <p class="eyebrow">Consultation</p>
        <h2 class="h2 statement">An Audit Finds the Gap. We Close It.</h2>
        <p class="body" style="margin-top:1.2rem">Nini Corporation is an independent organisation rendering consultation services on sustainable management, social and quality systems. We work with spinning, weaving, processing and stitching units — and the buyers who depend on them — to build compliance management systems that hold.</p>
        <ul class="feature__list" style="margin-top:1.6rem">
          <li>{TICK}<span>Quality management systems (ISO 9001) for textile manufacturing units</span></li>
          <li>{TICK}<span>Social and ethical systems built to withstand buyer audits</span></li>
          <li>{TICK}<span>Corrective action planning after a failed or conditional audit</span></li>
        </ul>
      </div>
      <div class="feature__media reveal reveal--depth reveal-d1 clipreveal">
        <img src="assets/img/process-inspection.jpg" alt="Inspection and documentation review" width="1920" height="1072" loading="lazy">
      </div>
    </div>
  </div>
</section>
{CTA_BAND}'''
    sizes["certifications.html"] = render("certifications.html", f"Certifications | {SITE['name']}",
        "ISO 9001 and ethical certification consultation for textile manufacturing units.", body)

    # Quality assurance
    body = page_hero("Quality Checked at Every Stage",
                     "From yarn testing to the sealed container, our inspection workflow is designed to catch issues before they become your problem.",
                     "assets/img/product-bath-towels.jpg", "Quality Assurance") + f'''
<section class="section"><div class="container">{approach_grid(QA)}</div></section>
{CTA_BAND}'''
    sizes["quality-assurance.html"] = render("quality-assurance.html", f"Quality Assurance | {SITE['name']}",
        "Four-point inspection, lab-verified yarn testing, daily in-line inspection and pre-shipment inspection.", body)

    # Portal — the differentiator. Detail drawn from the QMS development brief.
    # TODO: confirm which features are live before publishing. The source
    # document is a specification ("Develop a mobile application…"), so any
    # capability still in build should be worded as coming, not delivered.
    body = page_hero("Our Quality Management System",
                     "A mobile inspection app for our auditors and a web portal for you — one cloud system covering every inspection, report and quality record.",
                     "assets/img/process-inspection.jpg", "Client Portal &amp; Reporting") + f'''
<section class="section portal">
  <div class="container">
    <div class="portal__grid">
      <div class="reveal">
        <p class="eyebrow">Why It Matters</p>
        <h2 class="h2 statement">Evidence, Not Reassurance</h2>
        <p class="body" style="margin-top:1.2rem">
          Most buying houses tell you an order is on track. Ours shows you. Our auditors work
          from a mobile inspection app on the factory floor — AQL sample sizes calculated for
          them, pass and fail decided against the standard rather than by judgement, every
          defect photographed and tagged. The report is generated on the spot and lands in your
          portal, not in an inbox three days later.
        </p>
        <ul class="feature__list" style="margin-top:1.6rem">
          <li>{TICK}<span><strong>Recorded at the point of inspection</strong> — on the factory floor, against your standard, not written up from memory afterwards.</span></li>
          <li>{TICK}<span><strong>Nothing depends on arithmetic under pressure.</strong> Sample sizes and accept/reject limits are computed, not worked out by hand on a clipboard.</span></li>
          <li>{TICK}<span><strong>Searchable history</strong> by PO, item, vendor, factory, inspector or date — so a recurring defect is visible as a pattern, not a surprise.</span></li>
        </ul>
        <div style="margin-top:2rem"><a class="pill" href="contact.html#quote">Ask for a Demo {ARROW}</a></div>
      </div>
      <div class="reveal reveal--depth reveal-d1">{REPORT_CARD}</div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section--pad">
      <p class="eyebrow reveal">In the App</p>
      <h2 class="h2 statement reveal reveal-d1" style="margin-bottom:2.5rem">What Happens on the Factory Floor</h2>
    </div>
    {approach_grid([
      ("01","AQL Calculated, Not Estimated","The auditor enters order quantity, ready quantity and inspection level. Sample size and the major and minor accept/reject limits are derived from the AQL standard automatically."),
      ("02","Pass or Fail Decided by the Standard","Recorded defects are compared against the acceptance criteria and the result is returned by the system — removing the judgement call that inspection disputes usually turn on."),
      ("03","Every Defect Photographed","Photos are captured in the app and tagged by category, defect and location, with annotation on the image. Product, packaging, defects and measurements are each covered."),
      ("04","Measurements Against Tolerance","Entered measurements are checked against your specification and flagged the moment they fall outside tolerance."),
      ("05","Specifications Recalled, Not Retyped","Entering an item number recalls its construction, GSM, dimensions and packaging from previous inspections. The auditor verifies rather than re-keys."),
      ("06","Signed on Site","Inspector and factory representative sign on the screen, and both signatures are embedded in the report."),
      ("07","Works Without Internet","Inspections are saved locally and sync when a connection returns — because a great many factory floors do not have reliable coverage."),
      ("08","Report Generated On the Spot","One action produces the finished PDF: summary, tagged images, signatures. No retyping into a template afterwards."),
    ], "approach--8")}
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="split split--text-first">
      <div class="reveal">
        <p class="eyebrow">In Your Portal</p>
        <h2 class="h2 statement">What You See From Your Desk</h2>
        <p class="body" style="margin-top:1.2rem">
          The same system that runs the inspection gives you the record of it. Reports are
          retrievable by PO, item, vendor, customer, inspector or date, and the quality history
          builds into something you can actually read trends from.
        </p>
        <ul class="feature__list" style="margin-top:1.6rem">
          <li>{TICK}<span><strong>Vendor performance</strong> — pass and fail rates by mill, so you can see which partners hold quality and which drift.</span></li>
          <li>{TICK}<span><strong>Defect trends</strong> — the recurring faults across a programme, ranked, rather than one report at a time.</span></li>
          <li>{TICK}<span><strong>Product risk</strong> — the items that repeatedly cause problems, flagged before the next order is placed.</span></li>
          <li>{TICK}<span><strong>Full report archive</strong> — every inspection, downloadable as the PDF it was issued as.</span></li>
        </ul>
      </div>
      <div class="feature__media reveal reveal--depth reveal-d1 clipreveal">
        <img src="assets/img/process-production.jpg" alt="Production floor monitored through the quality management system" width="1920" height="1072" loading="lazy">
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section--pad">
      <p class="eyebrow reveal">Coverage</p>
      <h2 class="h2 statement reveal reveal-d1" style="margin-bottom:2.5rem">Every Inspection Stage, One System</h2>
    </div>
    <ul class="riskrow stagger">
      <li>Inline inspection</li>
      <li>Pre-final inspection</li>
      <li>Final random inspection (FRI)</li>
      <li>Loading inspection</li>
      <li>Re-inspection</li>
    </ul>
    <p class="pullquote reveal">
      One auditor, one device, a complete inspection report before they leave the factory.
    </p>
  </div>
</section>
{CTA_BAND}'''
    sizes["portal.html"] = render("portal.html", f"Quality Management System | {SITE['name']}",
        "A mobile inspection app and client web portal: automated AQL, photographic evidence, instant PDF reports and searchable quality history.", body)

    # Products
    cats = '''<article class="cat"><h3 class="h4">Home Textiles</h3>
      <ul class="cat__list"><li>Bar mops</li><li>Bathmats</li><li>Bathrobes</li><li>Bath towels</li><li>Pool towels</li><li>Bath sheets</li><li>Face towels</li><li>Hand towels</li><li>Terry bibs</li><li>Infant shirts</li><li>Bath blankets</li><li>Body blankets</li><li>Patient gowns</li><li>Thermal blankets</li><li>Woven diapers</li></ul>
      <p class="cat__note">Plus specialised sizes — tea, kitchen and neck towels — institutional and retail sheeting, pillow covers, curtains, comforters, cushions and embroidered products, regardless of order size.</p></article>
    <article class="cat"><h3 class="h4">Yarn &amp; Greige Fabric</h3>
      <p class="cat__note">Sourcing and inspection for both yarn and greige fabric. Our panel comprises high-volume units with in-house sizing and weaving — air jet and sulzer projectile. Our team plans yarn procurement, allocates machines and monitors weaving quality daily, then re-inspects before shipment.</p>
      <p class="cat__note"><strong>Yarn is tested</strong> for moisture content, weight, thin/thick places, neps, strength and hairiness against buyer tolerances, via reputable laboratories.</p></article>
    <article class="cat"><h3 class="h4">Ready-to-Cut Woven Fabric</h3>
      <p class="cat__note">Sourcing for all kinds of dyed, printed and yarn-dyed fabrics — including denims, shirting and sheeting in narrow and wider widths. We also provide pre-shipment inspection services for apparel clients.</p></article>
    <article class="cat"><h3 class="h4">Ready-to-Cut Knit Fabric</h3>
      <p class="cat__note">Trained staff for both tubular and open-width knitted fabrication. We handle orders from yarn stage through to final packaging and testing, checking shrinkage, needle lines, skewing and bowing — delivering maximum efficiency and minimum stress to garment manufacturers.</p></article>'''
    body = page_hero("Sourced Categories, Backed by Four-Point Inspection",
                     "Home textiles, yarn and greige fabric, and ready-to-cut woven and knit fabric — sourced through a vetted vendor panel.",
                     "assets/img/product-bath-towels.jpg", "Products") + f'''
<section class="section"><div class="container">{products_grid()}
  <div class="catgrid stagger" style="margin-top:clamp(2rem,4vw,3.5rem)">{cats}</div>
</div></section>
{CTA_BAND}'''
    sizes["products.html"] = render("products.html", f"Products | {SITE['name']}",
        "Bath towels, bathrobes, kitchen textiles, infant textiles, patient gowns, thermal blankets and more.", body)

    # Gallery
    body = page_hero("Inside the Supply Chain",
                     "Production floors, inspection benches and loading bays — the work behind the order.",
                     "assets/img/process-production.jpg", "Gallery") + f'''
<section class="section"><div class="container">{gallery_grid()}</div></section>
{CTA_BAND}'''
    sizes["gallery.html"] = render("gallery.html", f"Gallery | {SITE['name']}",
        "Production floors, inspection benches and export loading from our vendor panel.", body)

    # Feedback
    body = page_hero("Client Feedback",
                     "Trusted by buyers across three continents.",
                     "assets/img/product-bathrobes.jpg", "Feedback") + f'''
<section class="section"><div class="container">{testimonials_block()}</div></section>
<section class="section">
  <div class="container">
    <div class="contact">
      <div class="reveal">
        <p class="eyebrow">Tell Us How We Did</p>
        <h2 class="h2 statement">Your Feedback Shapes Our Service</h2>
        <p class="lead" style="margin-top:1.2rem">If you have worked with us, we would like to hear about it — what went well, and what did not.</p>
        {CONTACT_DETAILS}
      </div>
      {CONTACT_FORM}
    </div>
  </div>
</section>'''
    sizes["feedback.html"] = render("feedback.html", f"Feedback | {SITE['name']}",
        "Client feedback and testimonials for Nini Corporation.", body)

    # Contact
    body = page_hero("Let's Talk About Your Programme",
                     "Tell us what you need sourced, inspected or audited — we respond with next steps within one business day.",
                     "assets/img/process-shipping.jpg", "Contact Us") + f'''
<section class="section" id="quote">
  <div class="container">
    <div class="contact">
      <div class="reveal">
        <p class="eyebrow">Contact Us</p>
        <h2 class="h2 statement">Karachi Office</h2>
        {CONTACT_DETAILS}
      </div>
      {CONTACT_FORM}
    </div>
  </div>
</section>'''
    sizes["contact.html"] = render("contact.html", f"Contact Us | {SITE['name']}",
        f"Contact Nini Corporation — {SITE['addr1']}, {SITE['addr2']}.", body)

    return sizes


FAQS = [
    ("What does a buying house actually do?",
     "We represent you on the ground. We identify and vet factories, negotiate price and lead time, monitor production daily, audit compliance, inspect before shipment and handle export documentation — so you deal with one accountable partner instead of a dozen mills."),
    ("Where are you based?",
     f"Karachi, Pakistan — the country's textile and port capital. Our office is at {SITE['addr1']}, {SITE['addr2']}."),
    ("Which markets do you serve?",
     "Buyers across Europe, the United Kingdom and North America. We have done so since 1999."),
    ("What do you source?",
     "Textiles only. Home textiles, yarn and greige fabric, ready-to-cut woven fabric and ready-to-cut knit fabric. We are specialists rather than generalists."),
    ("What inspection standard do you work to?",
     "Four-point for fabric as standard, and AQL-based inspection for finished goods. If you have your own standard operating procedure, we implement yours instead."),
    ("Do you audit factories, or only inspect goods?",
     "Both. We conduct factory, social, security, technical and environmental audits against local, international and C-TPAT requirements — thousands of them to date."),
    ("Can you use our own audit checklist?",
     "Yes. We conduct audits to the customer's own checklist. If you do not have one, we use ours, which comprehensively covers all audit requirements."),
    ("How do we track an order in progress?",
     "Weekly status reports by email, plus a web portal with your own user ID and password for live updates. Inspections are recorded on site in our inspection app and issued as PDF reports."),
    ("Do you handle shipping and documentation?",
     "Yes. Shipment and logistics planning, container loading supervision, and verification of vendor shipment documents before they are submitted to the bank."),
    ("Is there a minimum order quantity?",
     "Our vendor panel covers institutional and retail production regardless of order size. Send us your specification and quantity and we will tell you honestly whether we are the right partner."),
]


def build_extras():
    sizes = {}

    # FAQs
    items = ""
    for i, (q, a) in enumerate(FAQS):
        items += (f'<details class="faq"><summary><span>{q}</span>'
                  f'<span class="faq__icon" aria-hidden="true"></span></summary>'
                  f'<div class="faq__body"><p>{a}</p></div></details>')
    body = page_hero("Frequently Asked Questions",
                     "The questions international buyers ask us most often, answered plainly.",
                     "assets/img/process-inspection.jpg", "FAQs") + f'''
<section class="section"><div class="container"><div class="faqlist stagger">{items}</div></div></section>
{CTA_BAND}'''
    sizes["faqs.html"] = render("faqs.html", f"FAQs | {SITE['name']}",
        "Common questions about sourcing, inspection, auditing and reporting with Nini Corporation.", body)

    # Privacy — scaffold, not legal advice
    body = page_hero("Privacy Policy",
                     "How Nini Corporation handles the information you share with us.",
                     "assets/img/process-shipping.jpg", "Privacy") + f'''
<section class="section">
  <div class="container"><div class="measure">
    <!-- ⚠ TEMPLATE ONLY. This is a structural scaffold, not legal advice.
         Have a qualified adviser complete it before publishing, especially if
         you handle data belonging to UK or EU residents (UK GDPR / GDPR). -->
    <div class="legalnote reveal">
      <strong>This page is a template.</strong> It sets out the right structure but the wording
      has not been reviewed by a lawyer. Complete each section — and have it checked — before
      publishing, particularly because you serve UK and EU buyers and may fall under GDPR.
    </div>
    <div class="prose reveal reveal-d1">
      <h2 class="h3">What we collect</h2>
      <p>When you contact us through this website we collect the name, company, email address,
         phone number and message you provide. We do not collect payment information here.</p>
      <h2 class="h3">Why we collect it</h2>
      <p>Solely to respond to your enquiry and, where a commercial relationship follows, to
         administer it.</p>
      <h2 class="h3">Who we share it with</h2>
      <p>[Complete: name any third parties — email host, analytics, CRM.]</p>
      <h2 class="h3">How long we keep it</h2>
      <p>[Complete: state your retention period.]</p>
      <h2 class="h3">Your rights</h2>
      <p>[Complete: access, correction, deletion, and how to exercise them. Required under
         UK GDPR / GDPR for UK and EU residents.]</p>
      <h2 class="h3">Contact</h2>
      <p>Questions about this policy: <a href="mailto:{SITE['email']}">{SITE['email']}</a></p>
    </div>
  </div></div>
</section>'''
    sizes["privacy-policy.html"] = render("privacy-policy.html", f"Privacy Policy | {SITE['name']}",
        "How Nini Corporation handles information shared through this website.", body)

    # Terms — scaffold
    body = page_hero("Terms of Use",
                     "The terms on which this website is provided.",
                     "assets/img/process-production.jpg", "Terms") + f'''
<section class="section">
  <div class="container"><div class="measure">
    <!-- ⚠ TEMPLATE ONLY — see note. Not legal advice. -->
    <div class="legalnote reveal">
      <strong>This page is a template.</strong> Structure only; the wording has not been legally
      reviewed. Have an adviser complete it before publishing.
    </div>
    <div class="prose reveal reveal-d1">
      <h2 class="h3">Use of this site</h2>
      <p>Content on this website is provided for general information about Nini Corporation's
         services. It does not constitute a contractual offer.</p>
      <h2 class="h3">Accuracy</h2>
      <p>We take care to keep information current but make no warranty that it is complete or
         error-free. [Complete as advised.]</p>
      <h2 class="h3">Intellectual property</h2>
      <p>The Nini Corporation name, logo and site content belong to Nini Corporation unless
         stated otherwise.</p>
      <h2 class="h3">Governing law</h2>
      <p>[Complete: state the governing jurisdiction — typically Pakistan.]</p>
      <h2 class="h3">Contact</h2>
      <p><a href="mailto:{SITE['email']}">{SITE['email']}</a></p>
    </div>
  </div></div>
</section>'''
    sizes["terms.html"] = render("terms.html", f"Terms of Use | {SITE['name']}",
        "Terms on which the Nini Corporation website is provided.", body)

    # 404
    body = f'''<section class="pagehero">
  <div class="pagehero__media"><img src="assets/img/process-production.jpg" alt="" width="1920" height="1072"></div>
  <div class="container">
    <p class="crumbs"><a href="index.html">Home</a> <span>/</span> Not found</p>
    <h1 class="h1">404 — Page Not Found</h1>
    <p class="lead">That page has moved or never existed. These are the places most people are heading.</p>
  </div>
</section>
<section class="section">
  <div class="container">
    {approach_grid([
      ("01","Products","Home textiles, yarn and greige fabric, woven and knit — the full sourced range."),
      ("02","Services","The eight services we run on every order, from negotiation to dispatch."),
      ("03","Client Portal","Inspection app, PDF reports and live order tracking with your own login."),
      ("04","Contact Us","Send a specification and we respond within one business day."),
    ])}
    <div style="margin-top:2.2rem;display:flex;gap:.9rem;flex-wrap:wrap">
      <a class="pill" href="index.html">Back to Home {ARROW}</a>
      <a class="pill pill--ghost" href="contact.html">Contact Us</a>
    </div>
  </div>
</section>'''
    sizes["404.html"] = render("404.html", f"Page Not Found | {SITE['name']}",
        "That page could not be found.", body, current="")

    return sizes


def build_capability():
    """Print-designed one-pager. Self-contained and light-themed: this is the
    source Chrome renders to PDF, so it must not depend on the site stylesheet."""
    svc = "".join(f"<li><strong>{t}</strong>{d}</li>" for _, t, d in SERVICES)
    proc = "".join(f"<li><strong>{t}</strong>{d}</li>" for _, t, d in PROCESS)
    qa = "".join(f"<li><strong>{t}</strong>{d}</li>" for _, t, d in QA)

    html = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>{SITE['name']} — Capability Statement</title>
<style>
  @page {{ size: A4; margin: 14mm 14mm 12mm; }}
  * {{ box-sizing: border-box; margin: 0; }}
  body {{ font: 10pt/1.45 "Helvetica Neue", Arial, sans-serif; color: #16180F; background: #fff; }}
  .rule {{ height: 3px; background: #8CC163; margin-bottom: 8mm; }}
  header {{ display: flex; justify-content: space-between; align-items: flex-start; gap: 10mm; margin-bottom: 5mm; }}
  h1 {{ font-size: 22pt; letter-spacing: -.02em; line-height: 1.05; }}
  h1 span {{ color: #5E8F3B; display: block; }}
  .tag {{ font-size: 7.5pt; letter-spacing: .16em; text-transform: uppercase; color: #5E8F3B; margin-top: 2mm; }}
  .meta {{ text-align: right; font-size: 8.5pt; color: #4F4F4F; line-height: 1.5; }}
  h2 {{ font-size: 10.5pt; letter-spacing: .1em; text-transform: uppercase; color: #5E8F3B;
       margin: 6mm 0 2.5mm; padding-bottom: 1.5mm; border-bottom: 1px solid #DDE3D6; }}
  p.intro {{ font-size: 10.5pt; line-height: 1.5; }}
  ul {{ list-style: none; padding: 0; columns: 2; column-gap: 8mm; }}
  li {{ break-inside: avoid; margin-bottom: 2.4mm; font-size: 8.7pt; color: #3F443A; line-height: 1.4; }}
  li strong {{ display: block; color: #16180F; font-size: 9.2pt; }}
  .cols {{ display: flex; gap: 8mm; }}
  .cols > div {{ flex: 1; }}
  .prods {{ columns: 3; column-gap: 6mm; font-size: 8.7pt; color: #3F443A; }}
  .prods li {{ margin-bottom: 1.4mm; }}
  .prods li::before {{ content: "— "; color: #8CC163; }}
  footer {{ margin-top: 7mm; padding-top: 3mm; border-top: 1px solid #DDE3D6;
            display: flex; justify-content: space-between; font-size: 8pt; color: #4F4F4F; }}
  .badge {{ display: inline-block; background: #F0F5EA; border: 1px solid #C7DDB2;
            color: #3F6A25; padding: 1mm 2.5mm; font-size: 7.5pt; margin: 0 1.5mm 1.5mm 0; }}
</style></head><body>
<div class="rule"></div>
<header>
  <div>
    <h1>{SITE['name']}<span>Capability Statement</span></h1>
    <p class="tag">{SITE['tagline']}</p>
  </div>
  <div class="meta">
    Established {SITE['founded']}<br>{SITE['addr1']}<br>{SITE['addr2']}<br>
    {SITE['phone1']}<br>{SITE['email']}
  </div>
</header>

<p class="intro">Nini Corporation has provided sourcing and inspection services since {SITE['founded']} to
companies across Europe, the United Kingdom and North America. We represent international buyers on the
ground in Karachi — not as a trading intermediary, but as the quality, compliance and delivery team
inside the supply chain. Our objective is unchanged since 1999: complete peace of mind for our clients.</p>

<h2>Services</h2>
<ul>{svc}</ul>

<h2>Process</h2>
<ul>{proc}</ul>

<div class="cols">
  <div>
    <h2>Quality Assurance</h2>
    <ul style="columns:1">{qa}</ul>
  </div>
  <div>
    <h2>Compliance &amp; Audit</h2>
    <p style="font-size:8.7pt;color:#3F443A;line-height:1.45">Factory, social, security, technical and
    environmental audits against local, international and C-TPAT requirements — thousands conducted to
    date. We audit to your checklist, or ours.</p>
    <p style="margin-top:3mm">
      <span class="badge">Social compliance</span><span class="badge">C-TPAT security</span>
      <span class="badge">Technical</span><span class="badge">Environmental</span>
      <span class="badge">ISO 9001 consultation</span>
    </p>
  </div>
</div>

<h2>Products Sourced</h2>
<ul class="prods">
  <li>Bar mops</li><li>Bathmats</li><li>Bathrobes</li><li>Bath towels</li><li>Pool towels</li>
  <li>Bath sheets</li><li>Face towels</li><li>Hand towels</li><li>Terry bibs</li><li>Infant shirts</li>
  <li>Bath blankets</li><li>Body blankets</li><li>Patient gowns</li><li>Thermal blankets</li>
  <li>Woven diapers</li><li>Tea &amp; kitchen towels</li><li>Sheeting &amp; pillow covers</li>
  <li>Curtains &amp; comforters</li><li>Yarn &amp; greige fabric</li><li>Ready-to-cut woven</li>
  <li>Ready-to-cut knit</li>
</ul>

<footer>
  <span>{SITE['name']} — {SITE['tagline']}</span>
  <span>{SITE['email']} · {SITE['phone1']}</span>
</footer>
</body></html>
'''
    path = os.path.join(OUT, "capability-statement.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return len(html)


def build_seo(pages):
    """sitemap.xml + robots.txt. Update BASE to the real domain before deploying."""
    BASE = "https://www.ninicorporation.com"
    urls = ""
    for name in sorted(pages):
        if name == "404.html":
            continue
        loc = BASE + "/" + ("" if name == "index.html" else name)
        pri = "1.0" if name == "index.html" else "0.7"
        urls += f"  <url><loc>{loc}</loc><priority>{pri}</priority></url>\n"

    sitemap = f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{urls}</urlset>\n'
    with open(os.path.join(OUT, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(sitemap)

    robots = f"User-agent: *\nAllow: /\n\nSitemap: {BASE}/sitemap.xml\n"
    with open(os.path.join(OUT, "robots.txt"), "w", encoding="utf-8") as f:
        f.write(robots)

    return len(sitemap), len(robots)


if __name__ == "__main__":
    total = {"index.html": build_index()}
    total.update(build_subpages())
    total.update(build_extras())
    cap = build_capability()
    sm, rb = build_seo(total)
    print(f"Built {len(total)} pages\n")
    for name in sorted(total):
        print(f"  {name:28} {total[name]:>7,} bytes")
    print(f"\n  sitemap.xml                {sm:>7,} bytes")
    print(f"  robots.txt                 {rb:>7,} bytes")
